w_des=6;
z_des=0.707;
r1=z_des*w_des;
s1=sqrt(w_des^2-r1^2);
R_dsr=[
    -r1+s1*1i;
    -r1-s1*1i;
    R_lon(3);
    R_lon(4)];
B_stab=B_lon(:,1);
gain=place(A_lon,B_stab,R_dsr);
%gain(1)=0;
A_lon_stab=A_lon-B_stab*gain;
A_stab=[A_lon_stab,zeros(4,5);zeros(5,4),A_lat];
[~,R_lon_stab]=eig(A_lon_stab);
R_lon_stab=diag(R_lon_stab);